spring:
  application:
    name: emoticon-lab-backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_USER}
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

# Gemini API Configuration
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
